version: '3.9'
services:
  nginx:
    image: nginx:1.21.6-alpine
    hostname: nginx
    container_name: nginx
    volumes: 
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - $PWD/nginx/certs/:/etc/nginx/conf.d/certs/
    networks:
      - metanet-private
      - metanet-public
    ports:
      - 8080:443
    cpus: 1
    mem_limit: 128m
  metabase:
    image: metabase/metabase-enterprise:v1.44.3
    hostname: metabase
    container_name: metabase
    networks:
      - metanet-private
networks: 
  metanet-private:
    driver: bridge
    internal: true
  metanet-public:
    driver: bridge